name: generate-lighthouse-score

on:
  #  Trigger worflow manually
  workflow_dispatch:
  schedule:
    - cron:  '15 * * * *'

env:
  GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

jobs:
    generate-lighthouse-score-build:
      strategy:
      #  Creates multiple jobs
        matrix:
         page: ["0:10", "10:20"]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - run: yarn
        - run: yarn start ${{matrix.page}}
