name: generate-lighthouse-score

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 * * * *'

env:
  GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

jobs:
    generate-lighthouse-score-build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - run: echo $GOOGLE_SHEET_ID
        - run: yarn
        - run: yarn start